### ISSUE TITLE
Potential issue with pseudo-numerical labels?

### ISSUE THREAD

**Issue by abarysh** [baryshnikova-lab/safe-java#2]
I'm attaching a Cytoscape session file and a functional annotation file. The node labels are numeric both in the network and in the annotation file. However, (I think) in Cytoscape they are stored as strings. When trying to Build at Step 1, you can an error "Cannot cast java.lang.Integer to java.lang.Double". I think this may be caused by how the numeric labels are treated when the annotation file is loaded: maybe they don't get converted into strings before matching? It sounds like all info related to node labels should always be stored as strings.

[TESTER.cys.zip](https://github.com/baryshnikova-lab/safe-java/files/569353/TESTER.cys.zip)

[SAFE_FunctionalTable_GO-BP.txt.zip](https://github.com/baryshnikova-lab/safe-java/files/569355/SAFE_FunctionalTable_GO-BP.txt.zip)

**Comment by jrrmzz** [comment]
I had a look. The problem is that even though "Map-based" distances is selected, the app tries to fetch weights from the selected value of the invisible Edge column dropdown. For this particular network, this happens to be an integer column, which triggers the cast exception.

So we have two issues:

1. Edge weights should only be extracted when the edge-weighted distance metric is selected.
2. We need to add support for integer edge weights. Right now, we assume all numeric weights are strictly double.

**Comment by abarysh** [comment]
Cool! yeah, let's make sure that edge weights are ignored when map-based is selected.
